### ISSUE TITLE
UI checklist for next update

### ISSUE THREAD

**Issue by sanghoonio** [pepkit/pephub#361]
- [x] After deleting the last view while it is currently selected, you can't unselect the deleted view because the reactselect gets disabled. Either add a check so that if view list is empty, or if currently selected view no longer exists in view list, unselect the view. 
- [ ] You can't unselect a schema once one is assigned (can change to other schema, just can't remove)
- [x] Add a choose schema modal you open by clicking on yellow 'no schema' button next to 'save' and 'discard' buttons. Maybe pass in the validation passed modal
- [x] In validation passed modal, make selectinput corner rounding consistent with button (rounded-1)
