### ISSUE TITLE
`v0.5.0` issue tracking

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#73]
After yesterday's (12/07/2022) meeting, I thought it would be helpful to create a *master issue* for what needs to be done to make a new release (`0.5.0`) and polish up a lot of things. I am sure I am missing some, so please feel free to edit, but this is what I have:

**Nathan L.:**
- [ ] #20 
- [x] #70
- [x] #37 
- [x] #69
- [x] #59 (better docs)
- [x] #67
- [x] #72
- [x] #68

**Alex:**
- [x] #64 

**Nathan S.:**
- [x] #89
- [x] #71
- [x] #78

**Alip:**
- [x] #61 
- [x] #63

**Comment by nleroy917** [comment]
Am I missing anything?

**Comment by nleroy917** [comment]
Something I was thinking about for all of these - if a user deletes a PEP, then they probably should be required to submit an access token in their header for that action to occur

**Comment by nsheff** [comment]
Definitely. All of the limited scope endpoints should require authorization like this. list, view details, edit, delete. For the latter 3, there should be nothing allowed without authorization. For "list", it can give a partial list without authorization.

**Comment by nleroy917** [comment]
## Meeting notes January 3rd, 2023
- Keep the database how it is for now... update in the future if we really need.  
- **nathan L** needs an `update_pep` function.
- `pepdbagent` needs to work regardless of the database schema.
- `pephub` should be concerned with converting yaml strings to peppy projects.
  - **to validate a project:** instantiate a `peppy.Project()` object from the yaml string (`from_pandas`). Then validate.
  - **to update a project:** instantiate a `peppy.Project()` object from the yaml string, pass to `pepdbagent`

**Comment by nleroy917** [comment]
## Notes from January 10th, 2023:
- try not to generate javascript with jinja
- We need to fix comma's breaking the csv parsing (not sure where this is happening)
  - serve `csv` from sample-table endpoints, **not json**
- production database needs to fit with the new `pepdbagent`
- we need to have the good documentation for the three steps.
- Alex needs to create documentation to provide code for how to update a pep in the database.
- ~Bump this to `v1.0.0` 👀~ Nvm...

**Comment by khoroshevskyi** [comment]
One more thing that l is not mentioned: 
Add admin to organization namespaces for user that is it's member
- [x] Make dropdown button (namespace choice) instead of plain text.
- [ ] Make org private project visible for user
- [x] Add right for editing and deleting this projects.

**Comment by nleroy917** [comment]
@nsheff Currently pephub shows I belong to no organizations (which isn't true). I'm wondering if the pephub GitHub app for OAuth is only requesting access to public orgs. Can we change it to request access to private orgs too so that these get pulled in?

**Comment by nleroy917** [comment]
Im going to close this in favor of the new `0.6.0` mega issue thread
