### ISSUE TITLE
Release 0.6.0 UI polishing 🧼 and authentication updates 🔐

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#90]
1. [x] On first "geo" namespace search hit, "View" link is broken. View link is not propogating tag
2. [x] On edit, "Project config" fetch is very slow. There may be 2 related problems here: timeout to wait for monaco editor before fetching, and then the time it's taking for the fetch of the actual data after the editor has loaded.
3. [x] Saving fails with "Network Error"
4. [x] geo_recent has "None" in project name, no links work
5. [x] on Eido validator page, link to PEP documentation is broken
6. [x] On main page, on "My PEPs" button, move icon to the left, like other labels.
7. [ ] validator is still not working with multi-file peps

**Comment by nleroy917** [comment]
## Updates for `v0.6.0` release:
 - [ ] #100 
 - [ ] #98 
 - [x] #94 
 - [x] #96 
 - [x] #97 
 - [x] #102 
 - [x] #99 
 - [x] #85 
 - [x] #57 
 - [x] #104 
 - [x] #105

**Comment by nsheff** [comment]
Well, I was thinking this would be 2 steps, a bunch these of just 0.5.0 things that were broken...

In other words, some of these I want to finish before we're done with 0.5.0. Some of them I marked as 0.6.0 since they seemed like a "next version" type of thing. Unless you think we can do 0.6.0 in the next day or two. If it's just a numbering disagreement then we should switch the next stuff to 0.7.0, but I'm just not sure it was worth changing everything around for that

**Comment by nleroy917** [comment]
We made a release for `0.5.0` and `0.5.1`, so that's why I was bringing them into `0.6.0`

**Comment by nsheff** [comment]
> We made a release for `0.5.0` and `0.5.1`, so that's why I was bringing them into `0.6.0`

Oh whoops, my mistake. I thought we were still on 0.5.0

**Comment by nleroy917** [comment]
> geo_recent has "None" in project name, no links work

This one was weird. the `name` attribute in the `peppy` Project representation was set to `None` and that was causing issues... It might be something to do with the way `geo_recent` is being loaded into pephub.

**Comment by nleroy917** [comment]
I've got lots of things pushed to `dev_nathan`. In a few days I should be done with most but a few might be worth a bigger discussion and require help:
1. Authentication Flow
2. Saving changes fail in production.

**Comment by nleroy917** [comment]
This will be closed since the latest version was released.
